### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by doowb** [tunnckoCore/put-value#1]
@tunnckoCore looks like you fixed [this bug](https://github.com/tunnckoCore/put-value/blob/master/index.js#L35) I was about to point out. Will you publish to npm? Thanks.

**Comment by tunnckoCore** [comment]
> fixed this bug

mm which bug? i can try to finish that repo this night.

**Comment by tunnckoCore** [comment]
but im a lil' bit confused what happens around these repos.. ;d

**Comment by doowb** [comment]
it was done in [this commit](https://github.com/tunnckoCore/put-value/commit/6d897bddbf93475321db7f3ede2874f07b110dbb#diff-168726dbe96b3ce427e7fedce31bb0bcR35).... the `value` was not being passed to `set`, but now it is.

I was just making the `upsert-value` lib to handle both setting and putting.

**Comment by tunnckoCore** [comment]
oo yea, i remember why i stopped, because the last test case. i can publish 0.1.0, but i always almost instantly release v1.

**Comment by tunnckoCore** [comment]
@doowb done

**Comment by doowb** [comment]
ty
